name: mvvm_page_generator
description: A Dart package for making MVVM page.
version: 1.0.2
repository: https://github.com/abdelrahmanbonna/mvvm_page_generator/tree/main/

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  path: ^1.8.0
  args: ^2.3.0
  shell: ^2.0.0
  file: ^6.1.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
